---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_USER }}" && echo "${{ secrets.DOCKERHUB_TOKEN }}"