name: Simple Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Run a simple command
        run: echo "Hello, world!"